### ISSUE TITLE
Federation breaks when user arrives without referrer

### ISSUE THREAD

**Issue by jeriox** [ephios-dev/ephios#1376]
```
Traceback (most recent call last):
  File "/home/staghios/.local/lib/python3.11/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
            ^^^^^^^^^^^^^^^^^^^^^^^^

During handling of the above exception ('referrer'), another exception occurred:
  File "/home/staghios/.local/lib/python3.11/site-packages/ephios/plugins/federation/views/api.py", line 80, in get
    else FederatedGuest.objects.get(url=self.request.GET["referrer"])
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/staghios/.local/lib/python3.11/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by jeriox** [comment]
closed by #1133
